package clases;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cliente.java
//  @ Date : 6/4/2020
//  @ Author : Jean Chuquimarca - Diego Merino - Raul Condolo
//
//

public class Cliente extends Persona {

    public String direccion;

    public Cliente(String direccion) {
        this.direccion = direccion;
    }

    public Cliente(String direccion, String cedula, String nombre, String apellido, String mail, String clave) {
        super(cedula, nombre, apellido, mail, clave);
        this.direccion = direccion;
    }

    public void ActualizarDireccion(Cliente cliente, String direccion){
        cliente.setDireccion(direccion);
    }
    
    public Cliente() {
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getCedula() {
        return cedula;
    }

    public void setCedula(String cedula) {
        this.cedula = cedula;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getClave() {
        return clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    @Override
    public String toString() {
        return "Cliente{" + "direccion=" + direccion + '}';
    }

}
