INSERT INTO `clase_final`.`Provincia` (`Provincia`) VALUES ('Loja');
INSERT INTO `clase_final`.`Provincia` (`Provincia`) VALUES ('Azuay');
INSERT INTO `clase_final`.`Provincia` (`Provincia`) VALUES ('Pichincha');
INSERT INTO `clase_final`.`Provincia` (`Provincia`) VALUES ('Guayas');
INSERT INTO `clase_final`.`Provincia` (`Provincia`) VALUES ('Zamora');
INSERT INTO `clase_final`.`Provincia` (`Provincia`) VALUES ('Esmeraldas');
INSERT INTO `clase_final`.`Provincia` (`Provincia`) VALUES ('Carchi');
INSERT INTO `clase_final`.`Provincia` (`Provincia`) VALUES ('Bolivar');

INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Loja', '1');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Calvas', '1');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Guayaquil', '4');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Quito', '3');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Zamora', '5');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Tulcan', '7');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Milagro', '4');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Cayambe', '3');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Mejia', '3');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('El Pangui', '5');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('San Lorenzo', '6');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Atacames', '6');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Cuenca', '2');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Paute', '2');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Mira', '7');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Guaranda', '8');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('San Miguel', '8');
INSERT INTO `clase_final`.`Canton` (`canton`, `idPro`) VALUES ('Bucay', '4');