package Clases;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Factura.java
//  @ Date : 6/4/2020
//  @ Author : Jean Chuquimarca - Diego Merino - Raul Condolo
//
//




public class Factura extends Pedido {
	public String leyenda;
	public int formaDePago;
	public double descuento;
	public double valorTotal;
	public Pedido pedido;
}
