package clases;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gerente.java
//  @ Date : 6/4/2020
//  @ Author : Jean Chuquimarca - Diego Merino - Raul Condolo
//
//




public class Gerente extends  Empleado {

    public Gerente() {
    }
    public Gerente(int turno, double sueldo, String cedula, String nombre, String apellido, String mail, String clave) {
        super(turno, sueldo, cedula, nombre, apellido, mail, clave);
    }
    
}
