package clases;
//
//

import java.io.Serializable;
import java.util.ArrayList;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Local.java
//  @ Date : 6/4/2020
//  @ Author : Jean Chuquimarca - Diego Merino - Raul Condolo
//
//
public class Local implements Serializable {

    public String direccion;
    public Pedido pedido;
    public Vendedor vendedor;
    public Bodeguero bodeguero;
    public Gerente gerente;
    public Inventario inventario;
    public String nombre;
    public String codigo;
    public ArrayList<Inventario> inventarioGeneral = new ArrayList<>();
    public ArrayList<Pedido> ArrayPedidos = new ArrayList<>();

    public Local(String direccion, Vendedor vendedor, Bodeguero bodeguero, Gerente gerente, String nombre, String codigo) {
        this.direccion = direccion;
        this.vendedor = vendedor;
        this.bodeguero = bodeguero;
        this.gerente = gerente;
        this.nombre = nombre;
        this.codigo = codigo;
    }

    public Local(String direccion, boolean estaDeTurno, Pedido pedido, Vendedor vendedor, Bodeguero bodeguero, Gerente gerente, String nombre, String codigo, Producto producto, int cantidad) {
        this.direccion = direccion;
        this.pedido = pedido;
        this.vendedor = vendedor;
        this.bodeguero = bodeguero;
        this.gerente = gerente;
        this.nombre = nombre;
        this.codigo = codigo;
        this.inventarioGeneral.add(new Inventario(cantidad, producto));
    }

    public Local() {
    }

    public void AgregarInventario(int cantidad, Producto producto){
        this.inventarioGeneral.add(new Inventario(cantidad, producto));
    }
    public void AgregarPedidos(String fecha, int estado, double valor, Cliente cliente){
        this.ArrayPedidos.add(new Pedido (fecha, estado, valor, cliente));
    }
    

    
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public Pedido getPedido() {
        return pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    public Vendedor getVendedor() {
        return vendedor;
    }

    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }

    public Bodeguero getBodeguero() {
        return bodeguero;
    }

    public void setBodeguero(Bodeguero bodeguero) {
        this.bodeguero = bodeguero;
    }

    public Gerente getGerente() {
        return gerente;
    }

    public void setGerente(Gerente gerente) {
        this.gerente = gerente;
    }

    public Inventario getInventario() {
        return inventario;
    }

    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public ArrayList<Inventario> getInventarioGeneral() {
        return inventarioGeneral;
    }

    public void setInventarioGeneral(ArrayList<Inventario> inventarioGeneral) {
        this.inventarioGeneral = inventarioGeneral;
    }

    public ArrayList<Pedido> getArrayPedidos() {
        return ArrayPedidos;
    }

    public void setArrayPedidos(ArrayList<Pedido> ArrayPedidos) {
        this.ArrayPedidos = ArrayPedidos;
    }
    

    @Override
    public String toString() {
        return "Local{" + "direccion=" + direccion + ", pedido=" + pedido + ", vendedor=" + vendedor + ", bodeguero=" + bodeguero + ", gerente=" + gerente + ", inventario=" + inventario + '}';
    }

}
