package Clases;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Local.java
//  @ Date : 6/4/2020
//  @ Author : Jean Chuquimarca - Diego Merino - Raul Condolo
//
//




public class Local {
	public String direccion;
	public boolean estaDeTurno;
	public Pedido pedido;
	public Vendedor vendedor;
	public Bodeguero bodeguero;
	public Gerente gerente;
	public Inventario inventario;
}
