/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.Bodeguero;
import clases.Inventario;
import clases.Local;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import logica.LogicaLocal;
import clases.Producto;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.LogicaBodeguero;
import logica.LogicaInventario;

/**
 *
 * @author diegomerino
 */
public class GUI_Bodeguero_V2 extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Bodeguero_V2
     */
    static LogicaLocal ObjLogLoc = new LogicaLocal();

    ArrayList<Local> ArrayLocales = new ArrayList<>();
    static ArrayList ArrayInventario = new ArrayList<Inventario>();
    ArrayList<Inventario> InventarioNuevo = new ArrayList<>();
    static boolean HayLocales;

    LogicaLocal objLogLoc = new LogicaLocal();
    LogicaBodeguero objLogBod = new LogicaBodeguero();
    LogicaInventario objLogInv = new LogicaInventario();
    
    Local local;
    Bodeguero bodeguero;
    int idLocal = 0;
    Inventario inventario;

    public GUI_Bodeguero_V2() {
        initComponents();
        try {
            LogicaLocal.LeerLocalesDAT(ArrayLocales);
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(GUI_Bodeguero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonAgregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jTextCod = new javax.swing.JTextField();
        jTextNombreLocal = new javax.swing.JTextField();
        jTextNom = new javax.swing.JTextField();
        jButtonAtras = new javax.swing.JButton();
        jTextPrec = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextCanti = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInventario = new javax.swing.JTable();
        jButtonGuardar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("INTRODUCIR DATOS DEL PRODUCTO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 171, -1, -1));

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setEnabled(false);
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 260, -1, -1));

        jLabel3.setText("Código");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 206, -1, -1));

        jLabel8.setText("Cedula");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 47, -1, -1));

        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 206, -1, -1));
        getContentPane().add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 44, 110, -1));

        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 206, -1, -1));

        jButtonIngresar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 44, 87, -1));
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 73, 110, -1));

        jTextCod.setEnabled(false);
        getContentPane().add(jTextCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 203, 80, -1));

        jTextNombreLocal.setEnabled(false);
        getContentPane().add(jTextNombreLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 137, 155, -1));

        jTextNom.setEnabled(false);
        getContentPane().add(jTextNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 203, 152, -1));

        jButtonAtras.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 87, 87, -1));

        jTextPrec.setEnabled(false);
        getContentPane().add(jTextPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 203, 80, -1));

        jLabel9.setText("Local");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 140, -1, -1));

        jLabel10.setText("clave");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 76, -1, -1));

        jLabel7.setText("Cantidad");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel11.setText("Bodeguero:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 44, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Agregar productos a Inventario/Local");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 6, 408, 20));

        jTextCanti.setEnabled(false);
        getContentPane().add(jTextCanti, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 80, 30));

        jTableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableInventario.setEnabled(false);
        jScrollPane1.setViewportView(jTableInventario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 308, 537, 154));

        jButtonGuardar.setText("Guardar Inventario");
        getContentPane().add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 510, -1, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 251, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        Local ObjLocal = ObjLogLoc.BuscarConBodeguero(ArrayLocales, jTextCedula.getText());
        int indexLocal = ArrayLocales.indexOf(ObjLocal);
        //Producto ObjProd = new Producto(this.jTextCod.getText(), this.jTextNom.getText(), Double.parseDouble(this.jTextPrec.getText()), this.jTextVenc.getText());
        //Inventario objInv = new Inventario(Integer.parseInt(this.jTextCanti.getText()), ObjProd);
        //ObjLocal.AgregarInventario(Integer.parseInt(this.jTextCanti.getText()), ObjProd);
        ArrayLocales.add(indexLocal, ObjLocal);
        try {
            LogicaLocal.EscribirLocalesDAT(ArrayLocales);
        } catch (IOException ex) {
            Logger.getLogger(GUI_Bodeguero.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        // TODO add your handling code here:
        bodeguero = new Bodeguero();
        try {
            bodeguero = objLogBod.ConsultarBodegueroConCedula(this.jTextCedula.getText());
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUI_Bodeguero_V2.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (bodeguero.getCedula().equals(this.jTextCedula.getText()) && bodeguero.getClave().equals(String.valueOf(this.jPassword.getPassword()))) {
            //Local ObjLocal = ObjLogLoc.BuscarConBodeguero(ArrayLocales, jTextCedula.getText());
            local = new Local();
            try {
                local = objLogLoc.ConsultarLocalIdConBodeguero(this.jTextCedula.getText());
                idLocal = objLogLoc.ConsultarIDLocal(local.getCodigo());
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(GUI_Bodeguero_V2.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.jTextNombreLocal.setText(local.getNombre());
            this.jTextCanti.setEnabled(true);
            this.jTextCod.setEnabled(true);
            this.jTextNom.setEnabled(true);
            this.jTextPrec.setEnabled(true);
            this.jTextCedula.setEnabled(false);
            this.jPassword.setEnabled(false);
            CargarInventario();
        } else {
            JOptionPane.showMessageDialog(null, "No existe", "Error", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            // TODO add your handling code here:
            objLogInv.LeerInventario(ArrayInventario, idLocal);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUI_Bodeguero_V2.class.getName()).log(Level.SEVERE, null, ex);
        }
        inventario = new Inventario();
        try {
            inventario = objLogInv.BuscarInventarioDelLocal(this.jTextCod.getText(), idLocal);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUI_Bodeguero_V2.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (inventario.getNombre() != null){
            this.jTextNom.setText(inventario.getNombre());
            this.jTextPrec.setText(String.valueOf(inventario.getPrecio()));
            this.jTextCanti.setText(String.valueOf(inventario.getCantidad()));
            this.jButtonAgregar.setEnabled(true);
        } else this.jButtonAgregar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Bodeguero_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Bodeguero_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Bodeguero_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Bodeguero_V2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Bodeguero_V2().setVisible(true);
            }
        });
    }

    void CargarInventario() {
        
        Object columnas[] = {
            "Codigo", "Nombre", "Cantidad", "Precio", "Vencimiento"
        };
        DefaultTableModel model = new DefaultTableModel(null, columnas);
        Local objLocal = ObjLogLoc.BuscarConBodeguero(ArrayLocales, jTextCedula.getText());
        this.jTableInventario.setModel(model);
        for (Inventario objInv : objLocal.getInventarioGeneral()) {
            String NewValor[] = {
                objInv.getProducto().getCodigo(),
                objInv.getProducto().getNombre(),
                String.valueOf(objInv.getCantidad()),
                String.valueOf(objInv.getProducto().getPrecio()),
                objInv.getProducto().getVencimiento()
            };
            model.addRow(NewValor);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInventario;
    private javax.swing.JTextField jTextCanti;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextCod;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextField jTextNombreLocal;
    private javax.swing.JTextField jTextPrec;
    // End of variables declaration//GEN-END:variables
}
